### PR TITLE
Simplify district seats correct seat numbers

### PR DESCRIPTION
**Pull request by Log234**
Implemented:
- Simplified the DistrictSeats in ElectionParameters.
- Corrected the incorrect data from SSB.
- API request for Parties
- API request for Districts

Test:
- Correct numbers for the election 1969
- Correct mapping between party codes and names
- Correct districts returned when searching for a specific year or all years
- Correct number of district seats returned with ElectionParameters

IMPORTANT!
The API update requires a small tweak to the client to correctly function with the new district seats implementation.

API v2.1 change:
parameters.districtSeats is now an integer instead of an array.
The pre distributed district seats can still be accessed in the metrics for each district.

### CODE REVIEW

**Comment by simendag** [comment]
@Log234 What was this "small tweak"? Do we still need to merge this PR? It's quite stale at this point. Given you are probably working on the new functionality for the API it would be wise to merge this first if it needs merging.

**Comment by Log234** [comment]
It appears as though I have already implemented #25 in this PR. It is a shame we didn't get it reviewed earlier or I wouldn't have implemented it a second time.

**Comment by simendag** [comment]
> It appears as though I have already implemented #25 in this PR. It is a shame we didn't get it reviewed earlier or I wouldn't have implemented it a second time.
> 
> I am seeing some ways to improve the implementation in this PR, so I will be pushing some changes.

So this will be merged along with the other changes in the end?

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Lavinia-api/Data/NOInitializer.cs  2
- Lavinia-api/Controllers/NOController.cs  1
         

Complexity decreasing per file
==============================
+ Lavinia-api/Data/CustomValidation.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-api/pullRequest?prid=5453119&bid=17878149)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ Lavinia-api/Data/CustomValidation.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-api/pullRequest?prid=5453119&bid=17878149)

**Comment by simendag** [comment]
> IMPORTANT!
The API update requires a small tweak to the client to correctly function with the new district seats implementation.

@Log234 What is this tweak?

**Comment by Log234** [comment]
> 
> 
> > IMPORTANT!
> > The API update requires a small tweak to the client to correctly function with the new district seats implementation.
> 
> @Log234 What is this tweak?

@simendag `requested-data-model.ts:78` districtSeats must be updated to be a number instead of a Dictionary<number>

**Comment by simendag** [comment]
> @simendag `requested-data-model.ts:78` districtSeats must be updated to be a number instead of a Dictionary

I'm not sure I'd characterise "changing 6 different files" as small, but that will definitely need to be done then... 

It means that if we merge with master and deploy this API, the client will be broken until it catches up. It is a shame this PR is so broad or we could have contained that aspect for a later release. Now we need to coordinate the releases, or have a broken application in the mean time.

**Comment by Log234** [comment]
> 
> 
> > @simendag `requested-data-model.ts:78` districtSeats must be updated to be a number instead of a Dictionary
> 
> I'm not sure I'd characterise "changing 6 different files" as small, but that will definitely need to be done then...
> 
> It means that if we merge with master and deploy this API, the client will be broken until it catches up. It is a shame this PR is so broad or we could have contained that aspect for a later release. Now we need to coordinate the releases, or have a broken application in the mean time.
> 
> The only thing we really _needed_ for this release was supporting a new API call (the party code to full name dictionary one).

Well, the PR has been sitting here for a year, so practices have changed since then.

**Comment by Log234** [comment]
@simendag Actually, we should make this API v3, as it breaks the current API. Then we will keep API v2 until we have migrated.

**Comment by simendag** [comment]
> @simendag Actually, we should make this API v3, as it breaks the current API. Then we will keep API v2 until we have migrated.

Agreed -- will you make the changes so that this is part of v3, so we can start development on the client features dependent on the party lookup reasonably soon (whenever we get the other features done for the next client release)?

**Comment by Log234** [comment]
> 
> 
> > @simendag Actually, we should make this API v3, as it breaks the current API. Then we will keep API v2 until we have migrated.
> 
> Agreed -- will you make the changes so that this is part of v3, so we can start development on the client features dependent on the party lookup reasonably soon (whenever we get the other features done for the next client release)?

Working on it.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Lavinia-api/Controllers/NOControllerv3.cs  7
         

Complexity decreasing per file
==============================
+ Lavinia-api/Data/CustomValidation.cs  -1
         

Clones added
============
- Lavinia-api/Controllers/NOController.cs  5
- Lavinia-api/Tests/ModelBuilderTests.cs  4
- Lavinia-api/Controllers/NOControllerv3.cs  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-api/pullRequest?prid=5453119&bid=17878149)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Lavinia-api/Controllers/NOControllerv3.cs  7
         

Complexity decreasing per file
==============================
+ Lavinia-api/Data/CustomValidation.cs  -1
         

Clones added
============
- Lavinia-api/Controllers/NOController.cs  5
- Lavinia-api/Tests/ModelBuilderTests.cs  4
- Lavinia-api/Controllers/NOControllerv3.cs  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-api/pullRequest?prid=5453119&bid=17878149)

**Pull request merged**
