### PR TITLE
Feature/remove old api versions

### LINKED ISSUE #42: docs: update README.md to reflect new version of SDK

### PR DESCRIPTION
**Pull request by Log234**
Removes API v1 and v2, and cleans up unused files.

Closes #42

### CODE REVIEW

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ Lavinia-api/Tests/UtilityTests.cs  -1
         

Clones removed
==============
+ Lavinia-api/Tests/ModelBuilderTests.cs  -4
+ Lavinia-api/Tests/UtilityTests.cs  -1
+ Lavinia-api/Utilities/CSVUtilities.cs  -4
+ Lavinia-api/Data/NOInitializer.cs  -1
+ Lavinia-api/Controllers/NOController.cs  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-api/pullRequest?prid=5992547&bid=19649757)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ Lavinia-api/Tests/UtilityTests.cs  -1
         

Clones removed
==============
+ Lavinia-api/Controllers/NOController.cs  -5
+ Lavinia-api/Data/NOInitializer.cs  -1
+ Lavinia-api/Utilities/CSVUtilities.cs  -4
+ Lavinia-api/Tests/ModelBuilderTests.cs  -4
+ Lavinia-api/Tests/UtilityTests.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-api/pullRequest?prid=5992547&bid=19649757)

**Comment by simendag** [comment]
We might consider updating the README to include the correct dependency in this PR, no?

I'm afraid I don't think there's any way I can properly review this amount of change in time for the meeting tomorrow; there's testing to do as well. Then again this likely isn't a change that will be noticed easily.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ Lavinia-api/Tests/UtilityTests.cs  -1
         

Clones removed
==============
+ Lavinia-api/Tests/UtilityTests.cs  -1
+ Lavinia-api/Data/NOInitializer.cs  -1
+ Lavinia-api/Tests/ModelBuilderTests.cs  -4
+ Lavinia-api/Controllers/NOController.cs  -5
+ Lavinia-api/Utilities/CSVUtilities.cs  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-api/pullRequest?prid=5992547&bid=19649757)

**Review by simendag — APPROVED** [review]
I think we should get this merged in after the data update, so that we have a better better outset for updating to .NET 6 LTS and any other tweaks we may need relating to that. Less code to update is better.

**Pull request merged**
